# Generated by Django 4.1.3 on 2022-11-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies_derevative", "0002_product_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
