# Generated by Django 4.1.3 on 2022-11-13 21:47

from django.db import migrations, models

import core


class Migration(migrations.Migration):

    dependencies = [
        ("companies_derevative", "0003_employee_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=200,
                validators=[core.validators.check_lengh_of_product],
            ),
        ),
    ]
