# Generated by Django 4.1.3 on 2022-11-13 21:58

from django.db import migrations, models

import core


class Migration(migrations.Migration):

    dependencies = [
        ("companies_derevative", "0004_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateField(null=True, validators=[core.validators.check_date]),
        ),
    ]
