# Generated by Django 4.1.3 on 2022-11-13 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies_derevative", "0005_alter_product_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="contact",
        ),
    ]
