# Generated by Django 4.1.3 on 2022-11-13 21:14

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commercial_network", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True, null=True)),
                ("time_update", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("debt", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency",
                    models.CharField(
                        choices=[("EUR", "EUR"), ("USD", "USD"), ("RUB", "RUB")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("Dealership", "Dealership"),
                            ("Distributor", "Distributor"),
                            ("Factory", "Factory"),
                            ("IndividualEntrepreneur", "Individualentrepreneur"),
                            ("LargeRetailChain", "Largeretailchain"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "commercial_network",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to="commercial_network.commercialnetwork",
                        verbose_name="торговая сеть",
                    ),
                ),
                (
                    "purveyor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
