# Generated by Django 4.1.3 on 2022-11-13 21:47

from django.db import migrations, models

import core


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="title",
            field=models.CharField(
                max_length=255, validators=[core.validators.check_lengh_of_chainlink]
            ),
        ),
    ]
